In [84]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print('shape : {}'.format(X.shape))
print('get_feature_names : {} \n'.format(vectorizer.get_feature_names()))

print(X.toarray()) 

shape : (4, 9)
get_feature_names : ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this'] 

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [86]:
print(X)

  (0, 1)	1
  (0, 2)	1
  (0, 6)	1
  (0, 3)	1
  (0, 8)	1
  (1, 5)	1
  (1, 1)	2
  (1, 6)	1
  (1, 3)	1
  (1, 8)	1
  (2, 4)	1
  (2, 7)	1
  (2, 0)	1
  (2, 6)	1
  (2, 3)	1
  (2, 8)	1
  (3, 1)	1
  (3, 2)	1
  (3, 6)	1
  (3, 3)	1
  (3, 8)	1


In [94]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    " This is the first document's name cou.",
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())

['and', 'document', 'first', 'is', 'name', 'one', 'second', 'the', 'third', 'this']
[[0.         0.37835697 0.46734613 0.30933162 0.59276931 0.
  0.         0.30933162 0.         0.30933162]
 [0.         0.6876236  0.         0.28108867 0.         0.
  0.53864762 0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.         0.51184851
  0.         0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.         0.38408524 0.         0.38408524]]


In [59]:
"""import des données"""
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)

In [60]:
len(twenty_train.data)

11314

In [61]:
"""Vous pouvez vérifier les noms des catégories cibles grâce à la commande
suivante ou en allant dans l'explorateur de variables
"""
twenty_train['target_names'] # print les catégories de textes

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [64]:
# print la première ligne du premier fichier texte
print("\n".join(twenty_train.data[0].split("\n")[:3])) 

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu


In [65]:

""" extraction des variables explicatives pour chaque texte, on va compter
les mots présents dans chaque texte grâce à la commande CountVectorizer
"""
from sklearn.feature_extraction.text import CountVectorizer
"""Vous pouvez savoir ce qu'elle fait en entrant dans la console la commande
?CountVectorizer"""
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train['data'])
X_train_counts.shape


(11314, 130107)

In [66]:
"""Produire les TF-IDF pour les termes dans chaque document"""
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(11314, 130107)

In [68]:
"""On peut s'économiser l'écriture de quelques lignes de code en
créant ce qu'on appelle un pipeline :
    -les noms 'vect' 'tfidf' 'clf' sont arbitraires mais seront utilisés par la suite
    -on utilisera le text_clf pour définir la pipeline"""
from sklearn.pipeline import Pipeline

text_clf_NB = Pipeline([('vect', CountVectorizer()), 
                        ('tfidf', TfidfTransformer()), 
                        ('clf', MultinomialNB())])

text_clf_NB = text_clf_NB.fit(twenty_train['data'], twenty_train['target'])

In [69]:
"""Performances du naive bayes"""
import numpy as np
twenty_test = fetch_20newsgroups(subset='test', shuffle=True)

predicted = text_clf.predict(twenty_test['data'])

test_CV =count_vect.transform( twenty_test['data'])

test_tfidf= tfidf_transformer.transform(test_CV)

predicted = clf.predict(test_tfidf)

np.mean(predicted == twenty_test['target'])

0.7738980350504514

In [70]:
"""Utilisation des support vector machines pour prédire la catégorie de texte"""
from sklearn.linear_model import SGDClassifier
text_clf_svm = Pipeline([('vect', CountVectorizer()), 
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, n_iter=5, random_state=42))])

text_clf_svm = text_clf_svm.fit(twenty_train['data'], twenty_train['target'])
predicted_svm = text_clf_svm.predict(twenty_test['data'])
np.mean(predicted_svm == twenty_test['target'])

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.8238183749336165

In [71]:
"""Grid search"""
"""Ici on créée une liste de paramètres qu'on souhaiterait optimiser
tous les noms des paramètres commencent par le nom du modèle utilisé
par exemple : vect__ngram_range, ici on dit au modèle d'utiliser les
unigrammes et les bigrammes et choisir ce qui fonctionne le mieux
"""
from sklearn.model_selection import GridSearchCV
parameters = {'vect__ngram_range': [(1, 1), (1, 2)], 
              'tfidf__use_idf': (True, False), 
              'clf__alpha': (1e-2, 1e-3)}

"""Ensuite on créée une istance de la gridsearch en entrant le modèle
choisi, les paramètres et l'instruction n_jobs=-1 qui indique à python
d'utiliser les différents processeurs de l'ordinateur pour réaliser
la grid search"""

gs_clf = GridSearchCV(text_clf_NB, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(twenty_train['data'], twenty_train['target'])

"""On utilise les commandes suivantes afin d'afficher les scores
du modèles en fonction des modèles choisis"""

"""==> La sortie produite par les commandes ci-dessous devraient être :
    The accuracy has now increased to ~90.6% for the NB classifier
    and the corresponding parameters are {‘clf__alpha’: 0.01, ‘tfidf__use_idf’: True, ‘vect__ngram_range’: (1, 2)}."""
print('gs_clf.best_score_  : {}'.format(gs_clf.best_score_))
print('gs_clf.best_params_  : {}'.format(gs_clf.best_params_))
print('gs_clf.best_estimator_ score :  {}'.format(gs_clf.best_estimator_.score(twenty_test['data'], twenty_test['target'])))

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


gs_clf.best_score_ 0.9067526957751458
gs_clf.best_params_ {'clf__alpha': 0.01, 'tfidf__use_idf': True, 'vect__ngram_range': (1, 2)}
gs_clf.best_estimator_ score 0.8344397238449283


'La sortie produite par les commandes ci-dessus devraient être :\n    The accuracy has now increased to ~90.6% for the NB classifier\n    and the corresponding parameters are {‘clf__alpha’: 0.01, ‘tfidf__use_idf’: True, ‘vect__ngram_range’: (1, 2)}.'

In [72]:
"""On réalise la même grid search pour les SVM"""
from sklearn.model_selection import GridSearchCV
parameters_svm = {'vect__ngram_range': [(1, 1), (1, 2)], 
                  'tfidf__use_idf': (True, False),
                  'clf-svm__alpha': (1e-2, 1e-3)}

gs_clf_svm = GridSearchCV(text_clf_svm, parameters_svm, n_jobs=-1)
gs_clf_svm = gs_clf_svm.fit(twenty_train['data'], twenty_train['target'])


gs_clf_svm.best_score_
gs_clf_svm.best_params_
gs_clf_svm.best_estimator_.score(twenty_test['data'], twenty_test['target'])

print('gs_clf_svm.best_score_  : {}'.format(gs_clf_svm.best_score_))
print('gs_clf_svm.best_params_  : {}'.format(gs_clf_svm.best_params_))
print('gs_clf_svm.best_estimator_ score :  {}'.format(gs_clf_svm.best_estimator_.score(twenty_test['data'], twenty_test['target'])))

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


gs_clf_svm.best_score_  : 0.8979140887396146
gs_clf_svm.best_params_  : {'clf-svm__alpha': 0.001, 'tfidf__use_idf': True, 'vect__ngram_range': (1, 2)}
gs_clf_svm.best_estimator_ score :  0.8331120552310144


In [74]:
"""On passe à de la modélisation à l'aide du package NLTK spécialisé dans le NLP"""
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('vect', CountVectorizer(stop_words='english')),
                     ('tfidf', TfidfTransformer()), 
                     ('clf', MultinomialNB())])

In [76]:
"""On réalise un stemming des mots dans les textes, c'est à dire qu'on les 
remplace par leur racine"""
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [77]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english", ignore_stopwords=True)

In [78]:
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

In [79]:
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')

In [80]:
text_mnb_stemmed = Pipeline([('vect', stemmed_count_vect), ('tfidf', TfidfTransformer()), 
                             ('mnb', MultinomialNB(fit_prior=False))])

In [81]:
text_mnb_stemmed = text_mnb_stemmed.fit(twenty_train['data'], twenty_train['target'])

In [82]:
predicted_mnb_stemmed = text_mnb_stemmed.predict(twenty_test['data'])

In [83]:
np.mean(predicted_mnb_stemmed == twenty_test['target'])

0.8167817312798725